site_name: LZAllright
strict: true
repo_name: vlaci/lzallright
repo_url: https://github.com/vlaci/lzallright
site_url: https://vlaci.github.io/lzallright

theme:
  name: material
  font:
    text: Open Sans
    code: Fira Code
  features:
    - toc.integrate
    - toc.follow
    - navigation.instant
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Home: index.md
  - API Documentation: api.md
  - Changelog: changelog.md

watch:
  - python

plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [python]
          options:
            allow_inspection: false
            separate_signature: true
            filters: ["!^_"]
            members_order: source

markdown_extensions:
  - pymdownx.snippets
  - toc:
      permalink: "#"
      toc_depth: 2
